# NumPy Practice

This notebook offers a set of exercises for different tasks with NumPy.

It should be noted there may be more than one different way to answer a question or complete an exercise.

Exercises are based off (and directly taken from) the quick introduction to NumPy notebook.

Different tasks will be detailed by comments or text.

For further reference and resources, it's advised to check out the [NumPy documentation](https://numpy.org/devdocs/user/index.html).

And if you get stuck, try searching for a question in the following format: "how to do XYZ with numpy", where XYZ is the function you want to leverage from NumPy.

In [1]:
# Import NumPy as its abbreviation 'np'
import numpy as np

In [6]:
# Create a 1-dimensional NumPy array using np.array()
a1= np.array([1,2,3])
a1
# Create a 2-dimensional NumPy array using np.array()
a2=np.array([[1,2,3],
             [4,5,6]])
a2
# Create a 3-dimensional Numpy array using np.array()
a3= np.array([[[1,2,3],
               [4,5,6],
               [7,8,9]],
               [[10,11,12],
               [13,14,15], 
               [16,17,18]]])
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

Now we've you've created 3 different arrays, let's find details about them.

Find the shape, number of dimensions, data type, size and type of each array.

In [8]:
# Attributes of 1-dimensional array (shape, 
# number of dimensions, data type, size and type)
a1.shape,a1.ndim,a1.dtype, a1.size, type(a1)

((3,), 1, dtype('int32'), 3, numpy.ndarray)

In [9]:
# Attributes of 2-dimensional array
a2.shape,a2.ndim,a2.dtype, a2.size, type(a2)

((2, 3), 2, dtype('int32'), 6, numpy.ndarray)

In [10]:
# Attributes of 3-dimensional array
a3.shape,a3.ndim,a3.dtype, a3.size, type(a3)

((2, 3, 3), 3, dtype('int32'), 18, numpy.ndarray)

In [13]:
# Import pandas and create a DataFrame out of one
# of the arrays you've created
import pandas as pd
df=pd.DataFrame(a2)

In [16]:
# Create an array of shape (10, 2) with only ones
ones=np.ones((10,2))
ones

array([[1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.],
       [1., 1.]])

In [18]:
# Create an array of shape (7, 2, 3) of only zeros
zeros=np.zeros((7,2,3))
zeros

array([[[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]],

       [[0., 0., 0.],
        [0., 0., 0.]]])

In [21]:
# Create an array within a range of 0 and 100 with step 3
range_array=np.arange(0,100,3)
range_array

array([ 0,  3,  6,  9, 12, 15, 18, 21, 24, 27, 30, 33, 36, 39, 42, 45, 48,
       51, 54, 57, 60, 63, 66, 69, 72, 75, 78, 81, 84, 87, 90, 93, 96, 99])

In [24]:
# Create a random array with numbers between 0 and 10 of size (7, 2)
randrom_array=np.random.randint(0,10,(7,2))
randrom_array

array([[0, 5],
       [4, 2],
       [3, 6],
       [2, 6],
       [2, 2],
       [4, 4],
       [1, 3]])

In [35]:
# Create a random array of floats between 0 & 1 of shape (3, 5)
random_array=np.random.uniform(0,1,(3,5))
random_array

array([[0.75594366, 0.55581641, 0.47692521, 0.06145005, 0.30797761],
       [0.06970897, 0.06464807, 0.3013922 , 0.84490456, 0.5318492 ],
       [0.83585833, 0.63212169, 0.46644815, 0.79320499, 0.66082309]])

In [38]:
# Set the random seed to 42
np.random.seed(42)

# Create a random array of numbers between 0 & 10 of size (4, 6)
random_array_2=np.random.randint(0,10,(4,6))
random_array_2

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

Run the cell above again, what happens?

Are the numbers in the array different or the same? Why do think this is?

In [41]:
# Create an array of random numbers between 1 & 10 of size (3, 7)
# and save it to a variable
r3= np.random.randint(0,10,(3,7))

# Find the unique numbers in the array you just created
np.unique(r3)
r3

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5],
       [9, 3, 5, 1, 9, 1, 9]])

In [42]:
# Find the 0'th index of the latest array you created
r3[0]

array([4, 1, 3, 6, 7, 2, 0])

In [43]:
# Get the first 2 rows of latest array you created
r3[:2]

array([[4, 1, 3, 6, 7, 2, 0],
       [3, 1, 7, 3, 1, 5, 5]])

In [44]:
# Get the first 2 values of the first 2 rows of the latest array
r3[:2,:2]

array([[4, 1],
       [3, 1]])

In [48]:
# Create a random array of numbers between 0 & 10 and an array of ones
# both of size (3, 5), save them both to variables
o=np.ones((3,5))
r4= np.random.randint(0,10,(3,5))
r4

array([[8, 6, 8, 7, 1],
       [0, 6, 6, 7, 4],
       [2, 7, 5, 2, 0]])

In [49]:
# Add the two arrays together
o+r4

array([[9., 7., 9., 8., 2.],
       [1., 7., 7., 8., 5.],
       [3., 8., 6., 3., 1.]])

In [50]:
# Create another array of ones of shape (5, 3)
o1=np.ones((5,3))
o1


array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [52]:
# Try add the array of ones and the other most recent array together
o1+r4.T

array([[9., 1., 3.],
       [7., 7., 8.],
       [9., 7., 6.],
       [8., 8., 3.],
       [2., 5., 1.]])

When you try the last cell, it produces an error. Why do think this is?

How would you fix it?

In [53]:
# Create another array of ones of shape (3, 5)
o2=np.ones((3,5))
o2

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [54]:
# Subtract the new array of ones from the other most recent array
r4-o2

array([[ 7.,  5.,  7.,  6.,  0.],
       [-1.,  5.,  5.,  6.,  3.],
       [ 1.,  6.,  4.,  1., -1.]])

In [55]:
# Multiply the ones array with the latest array
r4*o2

array([[8., 6., 8., 7., 1.],
       [0., 6., 6., 7., 4.],
       [2., 7., 5., 2., 0.]])

In [56]:
# Take the latest array to the power of 2 using '**'
r4**2

array([[64, 36, 64, 49,  1],
       [ 0, 36, 36, 49, 16],
       [ 4, 49, 25,  4,  0]])

In [57]:
# Do the same thing with np.square()
np.square(r4)

array([[64, 36, 64, 49,  1],
       [ 0, 36, 36, 49, 16],
       [ 4, 49, 25,  4,  0]])

In [58]:
# Find the mean of the latest array using np.mean()
np.mean(r4)

4.6

In [59]:
# Find the maximum of the latest array using np.max()
np.max(r4)

8

In [60]:
# Find the minimum of the latest array using np.min()
np.min(r4)

0

In [61]:
# Find the standard deviation of the latest array
np.std(r4)

2.776088375154268

In [62]:
# Find the variance of the latest array
np.var(r4)

7.706666666666666

In [63]:
# Reshape the latest array to (3, 5, 1)
r4.reshape(3,5,1)
r4

array([[8, 6, 8, 7, 1],
       [0, 6, 6, 7, 4],
       [2, 7, 5, 2, 0]])

In [64]:
# Transpose the latest array
r4.T

array([[8, 0, 2],
       [6, 6, 7],
       [8, 6, 5],
       [7, 7, 2],
       [1, 4, 0]])

What does the transpose do?

In [65]:
# Create two arrays of random integers between 0 to 10
# one of size (3, 3) the other of size (3, 2)
r5=np.random.randint(0,10,(3,3))
r6=np.random.randint(0,10,(3,2))

In [66]:
# Perform a dot product on the two newest arrays you created
np.dot(r5,r6)

array([[ 26,  48],
       [  8,  51],
       [ 66, 114]])

In [67]:
# Create two arrays of random integers between 0 to 10
# both of size (4, 3)
r7=np.random.randint(0,10,(4,3))
r8=np.random.randint(0,10,(4,3))
r7,r8

(array([[3, 4, 6],
        [6, 3, 6],
        [2, 5, 1],
        [9, 8, 4]]),
 array([[5, 3, 9],
        [6, 8, 6],
        [0, 0, 8],
        [8, 3, 8]]))

In [70]:
# Perform a dot product on the two newest arrays you created
np.dot(r7,r8)


ValueError: shapes (4,3) and (4,3) not aligned: 3 (dim 1) != 4 (dim 0)

It doesn't work. How would you fix it?

In [71]:
# Take the latest two arrays, perform a transpose on one of them and then perform 
# a dot product on them both
np.dot(r7,r8.T)

array([[ 81,  86,  48,  84],
       [ 93,  96,  48, 105],
       [ 34,  58,   8,  39],
       [105, 142,  32, 128]])

Notice how performing a transpose allows the dot product to happen.

Why is this?

Checking out the documentation on [`np.dot()`](https://docs.scipy.org/doc/numpy/reference/generated/numpy.dot.html) may help, as well as reading [Math is Fun's guide on the dot product](https://www.mathsisfun.com/algebra/vectors-dot-product.html).

Let's now compare arrays.

In [75]:
# Create two arrays of random integers between 0 & 10 of the same shape
# and save them to variables
r9=np.random.randint(0,10,(4,3))
r10=np.random.randint(0,10,(4,3))
r9,r10

(array([[7, 0, 0],
        [1, 1, 5],
        [6, 4, 0],
        [0, 2, 1]]),
 array([[4, 9, 5],
        [6, 3, 6],
        [7, 0, 5],
        [7, 4, 3]]))

In [77]:
# Compare the two arrays with '>'
r9>r10

array([[ True, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

What happens when you compare the arrays with `>`?

In [78]:
# Compare the two arrays with '>='
r9>=r10

array([[ True, False, False],
       [False, False, False],
       [False,  True, False],
       [False, False, False]])

In [79]:
# Find which elements of the first array are greater than 7
r9>7

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [80]:
# Which parts of each array are equal? (try using '==')
r9==r10

array([[False, False, False],
       [False, False, False],
       [False, False, False],
       [False, False, False]])

In [84]:
# Sort one of the arrays you just created in ascending order
r9.sort()
r9

array([[0, 0, 7],
       [1, 1, 5],
       [0, 4, 6],
       [0, 1, 2]])

In [85]:
# Sort the indexes of one of the arrays you just created
r9.argsort()

array([[0, 1, 2],
       [0, 1, 2],
       [0, 1, 2],
       [0, 1, 2]], dtype=int64)

In [86]:
# Find the index with the maximum value in one of the arrays you've created
r9.argmax()

2

In [87]:
# Find the index with the minimum value in one of the arrays you've created
r9.argmin()

0

In [88]:
# Find the indexes with the maximum values down the 1st axis (axis=1)
# of one of the arrays you created
r9.argmax(axis=1)

array([2, 2, 2, 2], dtype=int64)

In [89]:
# Find the indexes with the minimum values across the 0th axis (axis=0)
# of one of the arrays you created
r9.argmax(axis=0)

array([1, 2, 0], dtype=int64)

In [91]:
# Create an array of normally distributed random numbers
r11=np.random.randint(0,100,(5,6))
r11

array([[56, 88, 49, 22, 30, 93],
       [41, 98,  6, 15, 89, 59],
       [ 1,  0, 47, 11, 68, 36],
       [31,  8, 98, 18, 47, 79],
       [ 2, 19, 23, 53, 32, 23]])

In [97]:
# Create an array with 10 evenly spaced numbers between 1 and 100
r12=np.linspace(0,100,num=10)
r12

array([  0.        ,  11.11111111,  22.22222222,  33.33333333,
        44.44444444,  55.55555556,  66.66666667,  77.77777778,
        88.88888889, 100.        ])

## Extensions

For more exercises, check out the [NumPy quickstart tutorial](https://numpy.org/doc/stable/user/quickstart.html). A good practice would be to read through it and for the parts you find interesting, add them into the end of this notebook.

Pay particular attention to the section on broadcasting. And most importantly, get hands-on with the code as much as possible. If in dobut, run the code, see what it does.

The next place you could go is the [Stack Overflow page for the top questions and answers for NumPy](https://stackoverflow.com/questions/tagged/numpy?sort=MostVotes&edited=true). Often, you'll find some of the most common and useful NumPy functions here. Don't forget to play around with the filters! You'll likely find something helpful here.

Finally, as always, remember, the best way to learn something new is to try it. And try it relentlessly. If you get interested in some kind of NumPy function, asking yourself, "I wonder if NumPy could do that?", go and find out.